In [2]:
import numpy as np
import pandas as pd
import math

In [3]:
A = [[1,2,-1],[3,5,0],[-2,-1,2]]
B = [[10,11,12],[13,14,15],[16,17,18]]
C = [[2,3],[4,1]]
A = np.array(A)
B = np.array(B)
C = np.array(C)

In [4]:
VECTOR = [1,1]
V = np.array(VECTOR)
VECTORRR = [1,1,1]
VR = np.array(VECTORRR)

magnitude = np.linalg.norm(V)
print(magnitude)

magnitude = np.linalg.norm(VR)
print(magnitude)

1.4142135623730951
1.7320508075688772


In [5]:
# dimensions ->
# 3x2 :
"""
[ 1 3 ] [ a11 a12 ] 
[ 2 5 ] [ a21 a22 ] 
[ 6 7 ] [ a31 a32 ] 
""";

In [6]:
A.shape

(3, 3)

In [7]:
#Determinant
print(np.linalg.det(A))
#a11*a22 - (a12*a21) for 2x2

#for 3x3
"""
LAPLACE EXPANSION
det(A) * a 3x3 matrix
step 1: select column/row

suppose you select first row

a11*det[of the 2x2 matrix left if you cover the row and column of a11]
meaning -> 

+ a11*det[[a22,a23],[a32,a33]] 
- a12*det[[a21,a23],[a31,a33]]
+ a13*det[[a21,a22],[a31,a32]]

the signs ->
[+ - +] [a11 a12 a13]
[- + -] [a21 a22 a23]
[+ - +] [a31 a32 a33]

yuh
""";
one = np.array([[A[1,1],A[1,2]],[A[2,1],A[2,2]]])
two = np.array([[A[1,0],A[1,2]],[A[2,0],A[2,2]]])
three = np.array([[A[1,0],A[1,1]],[A[2,0],A[2,1]]])
one = np.linalg.det(one)*A[0,0]
two = np.linalg.det(two)*A[0,1]*-1
three = np.linalg.det(three)*A[0,2]
print(one+two+three)

-9.000000000000002
-9.0


In [8]:
print(A)
print()
print(A.transpose())
print()
print(A.transpose().transpose())

[[ 1  2 -1]
 [ 3  5  0]
 [-2 -1  2]]

[[ 1  3 -2]
 [ 2  5 -1]
 [-1  0  2]]

[[ 1  2 -1]
 [ 3  5  0]
 [-2 -1  2]]


In [9]:
#trace sums all the diagonals
#used to sum the total variance in covariance matrix
# tr(A) = tr(A^t)
#A^t -> transpose
print(np.trace(A))

8


In [10]:
3*A
#huh this works

array([[ 3,  6, -3],
       [ 9, 15,  0],
       [-6, -3,  6]])

In [11]:
#hb this
print(np.dot(A,A))
print(A.dot(A))
#whada hell

[[  9  13  -3]
 [ 18  31  -3]
 [ -9 -11   6]]
[[  9  13  -3]
 [ 18  31  -3]
 [ -9 -11   6]]


In [12]:
# special types of matrixes uwu desu daddy onii chan i hate nig
print(np.zeros((3,3)))
print()
print('symmetric matrix -> A=A^t')
print()
print('Diagonal matrix if all non-diagonal = 0')
print()
print(np.identity(3),"written as I3")
print()
print("Singular matrix if DET() is 0")
print("Nonsingular if DET() is not 0")
print()
print("Summing vector VECTOR is a vector which all elements")
print("is 1, youre on your own dumbass nuzzles you*")

[[0. 0. 0.]
 [0. 0. 0.]
 [0. 0. 0.]]

symmetric matrix -> A=A^t

Diagonal matrix if all non-diagonal = 0

[[1. 0. 0.]
 [0. 1. 0.]
 [0. 0. 1.]] written as I3

Singular matrix if DET() is 0
Nonsingular if DET() is not 0

Summing vector VECTOR is a vector which all elements
is 1, youre on your own dumbass nuzzles you*


In [13]:
#INVERSE AAAAHHAHAHAHHAHAHHA 
inverse = np.linalg.inv(C)
print(inverse)

"""
A^-1 =

  1       [a22  -a12] 
-----   *
Det(A)    [-a21  a11]
""";
lis = [[int(C[1,1]),-int(C[0,1])],[-int(C[1,0]),int(C[0,0])]]
spec = np.array(lis)
print((1/np.linalg.det(C))*(spec))

[[-0.1  0.3]
 [ 0.4 -0.2]]
[[-0.1  0.3]
 [ 0.4 -0.2]]


In [43]:
d = np.array([[4,3],[7,2]])
np.linalg.inv(d)

array([[-0.15384615,  0.23076923],
       [ 0.53846154, -0.30769231]])

In [47]:
-0.30769231 * -13

4.000000030000001

In [14]:
print("linear system unique if one solution")
print("infinitely many solution")
print("or no solution")
print()
print("if A is a square matrix")
print("if it is nonsingular -> unique soltuion det() is not 0")
print("else infinite or no solution")
print()
print("homogeneous if Ax = 0, all constant is 0")
print("in homogenuos solution either unique or inifite")
print()
print("consistent if one solution or infinitely")
print("inconsistent if no solution")
print()
print("trivial solution if all the x = 0")

linear system unique if one solution
infinitely many solution
or no solution

if A is a square matrix
if it is nonsingular -> unique soltuion det() is not 0
else infinite or no solution

homogeneous if Ax = 0, all constant is 0
in homogenuos solution either unique or inifite

consistent if one solution or infinitely
inconsistent if no solution

trivial solution if all the x = 0


In [106]:
#ELEMENTARY ROW OPERATIONS
"""
swap rows
multiply row by constant
add other row * any constant to current row
do this to achieve ROW ECHELOn fAG
hAaaAh

if divide by 0 error may mean infinite sol /  is 0?
""";
import numpy as np
import sys
 
n = int(input('Enter number of unknowns: '))
a = np.zeros((n,n+1))
x = np.zeros(n)
print('Enter Augmented Matrix Coefficients:')
for i in range(n):
    for j in range(n+1):
        a[i][j] = float(input( 'a['+str(i)+']['+ str(j)+']='))
for i in range(n):
    if a[i][i] == 0.0:
        sys.exit('Divide by zero detected!')
         
    for j in range(i+1, n):
        ratio = a[j][i]/a[i][i]
         
        for k in range(n+1):
            a[j][k] = a[j][k] - ratio * a[i][k]
 

x[n-1] = a[n-1][n]/a[n-1][n-1]

for i in range(n-2,-1,-1):
    x[i] = a[i][n]
     
    for j in range(i+1,n):
        x[i] = x[i] - a[i][j]*x[j]
     
    x[i] = x[i]/a[i][i]
 
print('\nThe solution is: ')
for i in range(n):
    print('X%d = %0.2f' %(i,x[i]), end = '\t')

Enter number of unknowns: 3
Enter Augmented Matrix Coefficients:
a[0][0]=0
a[0][1]=-1
a[0][2]=1
a[0][3]=0
a[1][0]=3
a[1][1]=-4
a[1][2]=1
a[1][3]=0
a[2][0]=3
a[2][1]=-5
a[2][2]=2
a[2][3]=0


SystemExit: Divide by zero detected!

C:\Users\sorki\anaconda3\lib\site-packages\IPython\core\interactiveshell.py:3465: UserWarning: To exit: use 'exit', 'quit', or Ctrl-D.
  warn("To exit: use 'exit', 'quit', or Ctrl-D.", stacklevel=1)


In [88]:
my_array = np.array([[12,16],[18,20],[14,16],[20,18]])
print(my_array.shape)
df = pd.DataFrame(my_array,columns=["Math","Science"])
df.describe()

(4, 2)


Math    Science
count   4.000000   4.000000
mean   16.000000  17.500000
std     3.651484   1.914854
min    12.000000  16.000000
25%    13.500000  16.000000
50%    16.000000  17.000000
75%    18.500000  18.500000
max    20.000000  20.000000

In [89]:
print(df.mean(axis=0))#average for each column
print()
print(df.mean(axis=1))#average for each row

Math       16.0
Science    17.5
dtype: float64

0    14.0
1    19.0
2    15.0
3    19.0
dtype: float64


In [90]:
#thier definition of mean for cokumn
print((1/4)*np.dot(my_array.transpose(),np.array([1,1,1,1])))
#n=4, 1n = [1,1,1,1]

[16.  17.5]


In [91]:
df.cov()

Math   Science
Math     13.333333  5.333333
Science   5.333333  3.666667

In [92]:
#cov for numpy
mean = (1/4)*np.dot(my_array.transpose(),np.array([1,1,1,1]))
coef = 1/(4-1) #n=4
print(my_array)
print()
print(np.array([1,1])*mean.transpose())
print()
print(my_array-np.array([1,1])*mean.transpose())
part1 = (my_array-(np.array([1,1])*mean.transpose())).transpose()
part2 = (my_array-(np.array([1,1])*mean.transpose()))
cov = part1.dot(part2)*coef
print(cov)
#n=4, 1n= [1,1] for the mean 


[[12 16]
 [18 20]
 [14 16]
 [20 18]]

[16.  17.5]

[[-4.  -1.5]
 [ 2.   2.5]
 [-2.  -1.5]
 [ 4.   0.5]]
[[13.33333333  5.33333333]
 [ 5.33333333  3.66666667]]


In [96]:
my_array = np.array([[10,11,15],[40,45,53]])
mean = (1/3)*np.dot(my_array.transpose(),np.array([1,1]))
coef = 1/(3-1) #n=4
print(my_array)
print()
print(np.array([1,1,1])*mean.transpose())
print()
print((my_array-(np.array([1,1,1])*mean.transpose())))
print(coef)
part1 = (my_array-(np.array([1,1,1])*mean.transpose())).transpose()
part2 = (my_array-(np.array([1,1,1])*mean.transpose()))
cov = part1.dot(part2)*coef
print(cov)

[[10 11 15]
 [40 45 53]]

[16.66666667 18.66666667 22.66666667]

[[-6.66666667 -7.66666667 -7.66666667]
 [23.33333333 26.33333333 30.33333333]]
0.5
[[294.44444444 332.77777778 379.44444444]
 [332.77777778 376.11111111 428.77777778]
 [379.44444444 428.77777778 489.44444444]]


In [80]:
ppp=(my_array-np.array([1,1,1])*mean.transpose())*3
print(ppp.transpose().dot(ppp)*(1/(6*3)))

[[294.44444444 332.77777778 379.44444444]
 [332.77777778 376.11111111 428.77777778]
 [379.44444444 428.77777778 489.44444444]]


In [97]:
print(my_array)
df = pd.DataFrame(my_array)
cov = np.array(df.cov())

[[10 11 15]
 [40 45 53]]


In [21]:
#det of cov -> generalized sample variance
#total sample is trace of cov
print("generalized sample variance",np.linalg.det(cov))
print("total sample variance",np.trace(cov))

generalized sample variance 20.444444444444446
total sample variance 17.0


In [22]:
#corr -> cov()/sd(x),sd(y)
df.corr()

Math  Science
Math     1.00000  0.76277
Science  0.76277  1.00000

In [98]:
print(cov)
print()
S = np.sqrt(np.diag(np.diag(cov)))
#take the diagonals of covariance and sqrt it (to get std)
print(np.diag(np.diag(cov)))
print()
print(S)
print()
Sin = np.linalg.inv(S)
print(Sin)
#inverse that shit

[[450. 510. 570.]
 [510. 578. 646.]
 [570. 646. 722.]]

[[450.   0.   0.]
 [  0. 578.   0.]
 [  0.   0. 722.]]

[[21.21320344  0.          0.        ]
 [ 0.         24.04163056  0.        ]
 [ 0.          0.         26.87005769]]

[[0.04714045 0.         0.        ]
 [0.         0.04159452 0.        ]
 [0.         0.         0.03721615]]


In [103]:
print(my_array)
y = np.array(my_array).transpose()
print(y)
df = pd.DataFrame(y)
cov = np.array(df.cov())
S = np.sqrt(np.diag(np.diag(cov)))
#take the diagonals of covariance and sqrt it (to get std)
Sin = np.linalg.inv(S)
corr = Sin.dot(cov.dot(Sin))
#inverse * cov * inverse
print(corr)

[[10 11 15]
 [40 45 53]]
[[10 40]
 [11 45]
 [15 53]]
[[1.         0.97986371]
 [0.97986371 1.        ]]


In [25]:
# Covariance show the direction of relationship and
#how strong dat shit be
#correlation show dat how closely intertwined that shit be
#ye

In [107]:
y = np.array([[1,-1,1],[3,-3,1],[3,-5,3]])
np.linalg.eig(y)

(array([-2.,  1.,  2.]),
 array([[ 0.        , -0.57735027,  0.40824829],
        [-0.70710678, -0.57735027,  0.40824829],
        [-0.70710678, -0.57735027,  0.81649658]]))

In [26]:
#linear transformations
data = np.array([[4,1],[-1,3],[3,5]]) #3x2
transy1 = np.array([[1,2],[1,2],[1,2]]) #2x2
transy2 = np.array([[3,-1],[3,-1],[3,-1]]) #2x2
y1 = data*transy1
y2 = data*transy2
y1 = y1.dot(np.array([[1],[1]]))
y2 = y2.dot(np.array([[1],[1]]))
np.concatenate((y1,y2), axis=1)

array([[ 6, 11],
       [ 5, -6],
       [13,  4]])

In [27]:
#eins dwei

In [28]:
# eigenvectors / values
#Av = lambda*v
#normalize eigenvectors
#eigendecomposition -> diagonalization theorem

In [29]:
A = np.array([[1,1],[0.5,1.5]])
print(A)
eigvals, eigvecs = np.linalg.eig(A)
print("Eigenvalues are: ",eigvals)
print("Eigenvectors are: ",eigvecs)

#lambda = 0.5
#-0.8844
#0.4472

#lambda = 2
#-0.7071
#-0.7071


[[1.  1. ]
 [0.5 1.5]]
Eigenvalues are:  [0.5 2. ]
Eigenvectors are:  [[-0.89442719 -0.70710678]
 [ 0.4472136  -0.70710678]]


In [30]:
#normalize dat shiii:
#whole number it works fine but small numbers not exactly
np.linalg.norm(np.float16([1000]))
print(np.linalg.norm(eigvecs,axis=1))
ye = np.array([eigvecs[0,0],eigvecs[0,1]])
print(np.linalg.norm(ye))

[1.14017543 0.83666003]
1.1401754250991378


In [31]:
def magnitude(vector): 
    return math.sqrt(sum(pow(element, 2) for element in vector))
magnitude(ye)

1.1401754250991378

In [32]:
# To normalise a vector
print(ye)
print(math.sqrt(np.sum(np.power(ye,2))))
print(ye/(math.sqrt(np.sum(np.power(ye,2)))))

[-0.89442719 -0.70710678]
1.1401754250991378
[-0.78446454 -0.62017367]


In [33]:
##TEST
ye = np.array([4,-9])
print(ye)
print(math.sqrt(np.sum(np.power(ye,2))))
print(ye/(math.sqrt(np.sum(np.power(ye,2)))))

[ 4 -9]
9.848857801796104
[ 0.40613847 -0.91381155]


In [34]:
##Linear dependence thing?
#A(cv) = c(Av) = c(lambda*v) = lambda*(cv)
"""
Put another way, if v is an eigenvector of A, then 1/2 v
, 0.123v , 100v, ..., etc, are also eigenvectors
of A corresponding to the same eigenvalue. So there are infinitely many eigenvectors
corresponding to lamdbda
""";

In [35]:
#manually calculate eigenvalue/vector
#(A-lambda*I)*v = 0
#det(A-lambda*I) = 0 called characteristic polynomial
#subsitute :) to find yo stuff

#e.g. given A and lambda
# Av = lambda*v
# [[1,-2],[3,-4]]*v = -1*v
# [[1,-2],[3,-4]]*[x1,x2] (augmented matrix) = -1*[x1,x2]
# x1 - 2x2  = -x1
# 3x1 - 4x2 = -x2

#2x1-2x2 = 0
#3x1-3x2 = 0

#linear independence if
#a0v0 + a1v1 + a2v2 = 0 then v0,v1,v2 are linearly independent
#lineraly dependent if these coefficients (a) are = 0

#linear decomposition:
#get the eigenvector matrix -> V
#get the matrix of eigenvalues in an identity (capital lambda)
"""
[lambda1   0 ]
[0    lambda2]
""";
#get the inverse of the eigenvector matrix V^-1
#A = V*(captial lambda)*V^-1
# to calculate A^p = V*(capital lambda)^p*V^-1

In [36]:
A = np.array([[1,1],[0.5,1.5]])
print(A)
eigvals, eigvecs = np.linalg.eig(A)
print("Eigenvalues are: ",eigvals)
print("Eigenvectors are: ",eigvecs)

[[1.  1. ]
 [0.5 1.5]]
Eigenvalues are:  [0.5 2. ]
Eigenvectors are:  [[-0.89442719 -0.70710678]
 [ 0.4472136  -0.70710678]]


In [37]:
g = np.array([[eigvals[0],0],[0,eigvals[1]]])
g

array([[0.5, 0. ],
       [0. , 2. ]])

In [40]:
Ainv = np.linalg.inv(A)
Ainv

array([[1., 0.],
       [0., 1.]])

In [39]:
Lindecomp = A.dot(g.dot(Ainv))
Lindecomp

array([[-0.25 ,  1.5  ],
       [-1.125,  2.75 ]])

In [41]:
2*2

4

nigga
